[TASK] Update start file

diff --git a/start b/start
--- a/start
+++ b/start
@@ -18,3 +18,13 @@ else
     echo "Installation of TYPO3 will be skipped because INSTALL_TYPO3 does not equal true..."
 fi
 
+# start open-ssh server if START_SSHD = true
+if [ "${START_SSHD}" = "true" ]; then
+    echo "Start openssh-server..."
+    if ! /etc/init.d/ssh start
+    then
+        echo "Error while starting openssh-server!"
+        exit 1
+    fi
+fi
+
